// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/house/house.proto

package house

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for House service

type HouseService interface {
	GetHouseInfo(ctx context.Context, in *InfoReq, opts ...client.CallOption) (*InfoResp, error)
}

type houseService struct {
	c    client.Client
	name string
}

func NewHouseService(name string, c client.Client) HouseService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.house"
	}
	return &houseService{
		c:    c,
		name: name,
	}
}

func (c *houseService) GetHouseInfo(ctx context.Context, in *InfoReq, opts ...client.CallOption) (*InfoResp, error) {
	req := c.c.NewRequest(c.name, "House.GetHouseInfo", in)
	out := new(InfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for House service

type HouseHandler interface {
	GetHouseInfo(context.Context, *InfoReq, *InfoResp) error
}

func RegisterHouseHandler(s server.Server, hdlr HouseHandler, opts ...server.HandlerOption) error {
	type house interface {
		GetHouseInfo(ctx context.Context, in *InfoReq, out *InfoResp) error
	}
	type House struct {
		house
	}
	h := &houseHandler{hdlr}
	return s.Handle(s.NewHandler(&House{h}, opts...))
}

type houseHandler struct {
	HouseHandler
}

func (h *houseHandler) GetHouseInfo(ctx context.Context, in *InfoReq, out *InfoResp) error {
	return h.HouseHandler.GetHouseInfo(ctx, in, out)
}
